// METHODS
const CREATE = 'CREATE';
const READ = 'READ';
const UPDATE = 'UPDATE';
const UPDATE_OTHERS = 'UPDATE_OTHERS';
const DELETE = 'DELETE';
const DELETE_OTHERS = 'DELETE_OTHERS';
const BULK_DELETE = 'BULK_DELETE';
const EXPORT = 'EXPORT';
const IMPORT = 'IMPORT';
const FUSE = 'FUSE';
const DUPLICATE = 'DUPLICATE';
const SHARE = 'SHARE';
const TO_ASSIGN = 'TO_ASSIGN';
const USER_MANAGEMENT = 'USER_MANAGEMENT';
const ENTERPRISE_MANAGEMENT = 'ENTERPRISE_MANAGEMENT';
const CUSTOM_TAGS_MANAGEMENT = 'CUSTOM_TAGS_MANAGEMENT';
const LOST_REASONS_MANAGEMENT = 'LOST_REASONS_MANAGEMENT';
const ACT_TYPES_MANAGEMENT = 'ACT_TYPES_MANAGEMENT';
const CUSTOM_FIELDS_MANAGEMENT = 'CUSTOM_FIELDS_MANAGEMENT';
const ME = 'ME';
const GROUP = 'GROUP';
const ALL = 'ALL';

export {
  ME,
  GROUP,
  ALL,
  CREATE,
  READ,
  UPDATE,
  UPDATE_OTHERS,
  DELETE,
  DELETE_OTHERS,
  BULK_DELETE,
  EXPORT,
  IMPORT,
  FUSE,
  DUPLICATE,
  SHARE,
  TO_ASSIGN,
  USER_MANAGEMENT,
  ENTERPRISE_MANAGEMENT,
  CUSTOM_TAGS_MANAGEMENT,
  LOST_REASONS_MANAGEMENT,
  ACT_TYPES_MANAGEMENT,
  CUSTOM_FIELDS_MANAGEMENT,
};
