/* Permissions */
const PERMISSIONS_ACTIVITIES = 'ACTIVITIES';
const PERMISSIONS_NOTES = 'NOTES';
const PERMISSIONS_FILES = 'FILES';
const PERMISSIONS_CONTACTS = 'CONTACTS';
const PERMISSIONS_COMPANIES = 'COMPANIES';
const PERMISSIONS_DEALS = 'DEALS';
const PERMISSIONS_PIPELINES = 'PIPELINES';
const PERMISSIONS_TAGS = 'TAGS';
const PERMISSIONS_USERS = 'USERS';
const PERMISSIONS_ADMIN = 'ADMIN_P';
const PERMISSIONS_SETTINGS = 'CONFIG_P';
const PERMISSIONS_GROUP_CONTACT = 'CONTACT';
const PERMISSIONS_GROUP_COMPANY = 'COMPANY';
const PERMISSIONS_GROUP_DEAL = 'DEAL';
const PERMISSIONS_ALL = 'all';

export {
  PERMISSIONS_ACTIVITIES,
  PERMISSIONS_NOTES,
  PERMISSIONS_FILES,
  PERMISSIONS_CONTACTS,
  PERMISSIONS_COMPANIES,
  PERMISSIONS_DEALS,
  PERMISSIONS_PIPELINES,
  PERMISSIONS_TAGS,
  PERMISSIONS_USERS,
  PERMISSIONS_ADMIN,
  PERMISSIONS_SETTINGS,
  PERMISSIONS_GROUP_CONTACT,
  PERMISSIONS_GROUP_COMPANY,
  PERMISSIONS_GROUP_DEAL,
  PERMISSIONS_ALL,
};
