export const data = {
  formContact: {
    __typename: 'formContact',
    socialMedias: [],
    phones: [],
  },
  appControl: {
    __typename: 'appControl',
    isLogged: false,
    isLoading: false,
  },
  userCurrent: {
    __typename: 'userCurrent',
    id: null,
    user: {
      __typename: 'User',
      id: null,
      email: null,
      lastName: null,
      name: null,
    },
    enterprise: {
      __typename: 'Enterprise',
      id: null,
      name: null,
    },
    integrations: [],
    emailTemplatesOrder: [],
    defaultEnterprise: null,
    profileUrl: null,
    typeUser: '',
    enterprises: [],
    membersGroup: [],
    permissionsRol: [],
    permissionsGroup: [],
  },
  modals: [
    {
      __typename: 'modal',
      id: 'signUp',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'sendEmail',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'createTemplateEmail',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'deleteTemplateEmail',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'createNote',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'createComment',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'createActivity',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'createActivityType',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'modalEffective',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'modalEffectiveActivity',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'modalEffectiveHistoryActivity',
      status: false,
      isEdit: false,
      item: null,
    },
    {
      __typename: 'modal',
      id: 'modalFiltersChart',
      status: false,
      isEdit: false,
      item: null,
    },
  ],

  errors: [],
  successes: [],
  filtersChartsGlobal: {
    __typename: 'filtersChartsGlobal',
    users: [],
    periodPredefined: [],
  },
  filtersChartsDefault: {
    __typename: 'filtersChartsDefault',
    activityTypes: [],
    users: [],
    pipelines: [],
    stages: [],
  },
  charts: [
    {
      __typename: 'chart',
      id: 'card-convertionRate',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-opportunitySales',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-closedDeals',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-closedDealsBySalesman',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-averageDaysInPipeline',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-wonDealsEarningValue',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-totalIncomeGoal',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-lostDeals',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-convertionRatio',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-sentEmails',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-bookedActivities',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-completedActivities',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-effectiveActivities',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-rebookedActivities',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-expiredActivities',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-ineffectiveActivities',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-openEmails',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-openRateEmails',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-totalOpenDeals',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-newDeals',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-advancedDeals',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'card-rottenDeals',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'line-convertionRate',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'line-opportunitySales',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'line-totalIncomeGoal',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'line-salesGrowthMonthly',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'line-opportunitySalesByWeek',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'line-salesCycleByMonth',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'line-throughTimeLostRate',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-stageConvertionRate',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-wonDealsEarningValue',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-opportunitySales',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-activityTypeByStage',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-dealDurationByStage',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-activitiesBySalesman',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-activitiesByWeek',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-uncompletedActivitiesByStage',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-expiredActivitiesByStage',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-salesCycleByStage',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'bar-lostDealsByStage',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'donut-lostReason',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'table-activityTypeByStage',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'table-lostOpportunities',
      filtersFull: '',
    },
    {
      __typename: 'chart',
      id: 'table-rebookedActivities',
      filtersFull: '',
    },
  ],
};
